apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contador-ingress
  annotations:
    # Usar el Ingress Controller de NGINX
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: contador.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: contador-service # Usaremos este nombre para el Service
            port:
              number: 8080
