apiVersion: v1
kind: Service
metadata:
  name: contador-service
spec:
  selector:
    app: contador  # Debe coincidir con labels de tu deployment
  ports:
  - port: 80
    targetPort: 5000  # Puerto interno del contenedor
  type: NodePort  # Para Minikube

